"""Curated reading syllabus for Travis. No proprietary full-text content.

Historical translations are downloadable for private local study where lawful.
Project Gutenberg marks works as public domain in the US; translations and
jurisdictions must be checked separately. Modern Jung books are reference-only.
All concept summaries are newly authored educational notes, not quotations.
"""
from __future__ import annotations

SCHEMA_VERSION = 1

# id, author, title, original publication date, translator, subject, Gutenberg ID
HISTORICAL_WORKS = (
    ("kant-pure","Immanuel Kant","The Critique of Pure Reason","1781/1787","J. M. D. Meiklejohn","epistemologia",4280),
    ("kant-ethics","Immanuel Kant","Fundamental Principles of the Metaphysic of Morals","1785","Thomas Kingsmill Abbott","ética",5682),
    ("kant-practical","Immanuel Kant","The Critique of Practical Reason","1788","histórica","ética",5683),
    ("james-varieties","William James","The Varieties of Religious Experience","1902","original inglês","psicologia da religião",621),
    ("james-psychology-1","William James","The Principles of Psychology, Volume I","1890","original inglês","psicologia",57628),
    ("james-psychology-2","William James","The Principles of Psychology, Volume II","1890","original inglês","psicologia",57634),
    ("freud-dreams","Sigmund Freud","The Interpretation of Dreams","1899/1900","A. A. Brill","psicanálise histórica",66048),
    ("freud-on-dreams","Sigmund Freud","On Dreams","1901","M. D. Eder","psicanálise histórica",75333),
    ("plato-republic","Platão","The Republic","c. 375 a.C.","Benjamin Jowett","filosofia clássica",1497),
    ("marcus-meditations","Marco Aurélio","Thoughts of Marcus Aurelius Antoninus","século II","George Long","estoicismo",15877),
    ("laozi-tao","Laozi","The Tao Teh King","antiguidade","James Legge","taoismo",216),
    ("buddhism-dhammapada","Tradição budista","The Dhammapada","antiguidade","F. Max Müller","budismo",2017),
)

BOOKS = tuple(
    dict(id=key,author=author,title=title,originalDate=original,
         translator=translator,subject=subject,
         textLanguage="en",
         sourceUrl="https://www.gutenberg.org/ebooks/"+str(pg),
         fetchUrl="https://www.gutenberg.org/cache/epub/"+str(pg)+"/pg"+str(pg)+".txt",
         pgId=pg,access="historic_public_domain_edition",
         rightsNote="Domínio público assinalado nos EUA; edição/tradução histórica. Confirmar legislação local antes de qualquer redistribuição.")
    for key,author,title,original,translator,subject,pg in HISTORICAL_WORKS
)

# These bibliography records are never bulk-downloaded automatically.
REFERENCES = (
    dict(id="jung-archetypes-work",author="Carl Gustav Jung",
         title="The Archetypes and the Collective Unconscious (Collected Works 9/I)",
         sourceUrl="https://iaap.org/resources/academic-resources/collected-works-abstracts/volume-9-1-archetypes-collective-unconscious/",
         subject="psicologia analítica",access="bibliography_only_copyrighted",textLanguage="en"),
    dict(id="jung-aion-work",author="Carl Gustav Jung",
         title="Aion: Researches into the Phenomenology of the Self (Collected Works 9/II)",
         sourceUrl="https://iaap.org/resources/academic-resources/collected-works-abstracts/volume-9-2-aion-researches-phenomenology-self/",
         subject="psicologia analítica",access="bibliography_only_copyrighted",textLanguage="en"),
    dict(id="jung-two-essays-work",author="Carl Gustav Jung",
         title="Two Essays on Analytical Psychology (Collected Works 7)",
         sourceUrl="https://iaap.org/resources/academic-resources/collected-works-abstracts/volume-7-two-essays-analytical-psychology/",
         subject="psicologia analítica",access="bibliography_only_copyrighted",textLanguage="en"),
)

# (id, author, subject, name, summary, source, epistemic_status)
# No quotation marks or direct extracts from works still under copyright.
CARDS = (
("jung-archetype","Carl Gustav Jung","psicologia analítica","Arquétipos",
 "Na psicologia de Jung, arquétipos são padrões organizadores hipotéticos que se exprimem em imagens, narrativas, símbolos e motivos recorrentes. O conceito ajuda a interpretar sonhos e mitos, mas a existência de arquétipos universais herdados não está estabelecida como lei empírica. Distinguir interpretação simbólica de medição científica.",
 "https://iaap.org/jung-analytical-psychology/analytical-psychology/","theory"),
("jung-collective","Carl Gustav Jung","psicologia analítica","Inconsciente coletivo",
 "Jung propôs, além do inconsciente pessoal ligado à biografia, um nível coletivo que estruturaria tendências para produzir símbolos partilhados. É uma hipótese da psicologia analítica; não equivale a uma base de dados real de memórias partilhadas nem é prova de herança literal de recordações.",
 "https://iaap.org/jung-analytical-psychology/analytical-psychology/","theory"),
("jung-shadow","Carl Gustav Jung","psicologia analítica","Sombra",
 "Na tradição junguiana, a sombra representa aspectos da personalidade que o ego rejeita, nega ou desconhece. A prática reflexiva proposta é reconhecer projeções e contradições pessoais sem reduzir qualquer comportamento a um arquétipo. Não diagnosticar pessoas a partir de um símbolo.",
 "https://iaap.org/resources/academic-resources/collected-works-abstracts/volume-9-2-aion-researches-phenomenology-self/","theory"),
("jung-individuation","Carl Gustav Jung","psicologia analítica","Individuação",
 "Processo descrito por Jung de integração progressiva de aspectos conscientes e inconscientes e desenvolvimento de uma vida psíquica mais diferenciada. É um ideal interpretativo de integração pessoal, não um marcador clínico de consciência ou um algoritmo automático de autoaperfeiçoamento.",
 "https://iaap.org/jung-analytical-psychology/short-articles-on-analytical-psychology/individuation-2/","theory"),
("jung-persona","Carl Gustav Jung","psicologia analítica","Persona",
 "A persona é o papel social e a imagem que uma pessoa apresenta nas relações e instituições. Jung distinguiu essa adaptação exterior da totalidade da personalidade. Serve como instrumento interpretativo, não como rótulo definitivo da identidade de alguém.",
 "https://iaap.org/jung-analytical-psychology/short-articles-on-analytical-psychology/persona-2/","theory"),
("jung-self","Carl Gustav Jung","psicologia analítica","Self e totalidade",
 "O Self junguiano é um conceito de totalidade e organização da psique, distinto do ego consciente. É relevante para compreender narrativas de sentido e símbolos religiosos na psicologia analítica; não deve ser confundido com demonstração de existência de uma entidade espiritual ou consciência numa máquina.",
 "https://iaap.org/jung-analytical-psychology/short-articles-on-analytical-psychology/the-self-2/","theory"),
("jung-anima","Carl Gustav Jung","psicologia analítica","Anima e animus",
 "Na formulação histórica de Jung, anima e animus representam figuras simbólicas de complementaridade psíquica. A terminologia foi construída em pressupostos de género da época; interpretar criticamente esses pressupostos e não os utilizar para classificar identidades de pessoas reais.",
 "https://iaap.org/resources/academic-resources/collected-works-abstracts/volume-7-two-essays-analytical-psychology/","theory"),
("jung-complexes","Carl Gustav Jung","psicologia analítica","Complexos afetivos",
 "Complexos são organizações de emoções, memórias e associações que podem influenciar atenção e reação sem que a pessoa tenha plena consciência. É uma noção histórica da psicologia analítica; observações de associações não autorizam diagnóstico psicológico automático.",
 "https://iaap.org/jung-analytical-psychology/analytical-psychology/","theory"),
("jung-dreams","Carl Gustav Jung","psicologia analítica","Sonhos e compensação",
 "Jung interpretou sonhos como possíveis expressões simbólicas que compensam atitudes conscientes. Uma interpretação de sonhos deve ser apresentada como hipótese entre alternativas, nunca como previsão factual, mensagem sobrenatural garantida ou diagnóstico psicológico.",
 "https://iaap.org/resources/academic-resources/collected-works-abstracts/volume-7-two-essays-analytical-psychology/","theory"),
("jung-synchronicity","Carl Gustav Jung","psicologia analítica","Sincronicidade",
 "Conceito de coincidências vividas como significativas sem uma relação causal conhecida. Experiências pessoais de significado podem ser importantes, mas não demonstram uma força física oculta. É necessário avaliar coincidências, seleção de exemplos e explicações estatísticas.",
 "https://iaap.org/jung-analytical-psychology/short-articles-on-analytical-psychology/the-self-2/","theory"),
("jung-symbols","Carl Gustav Jung","psicologia analítica","Símbolos, mitos e espiritualidade",
 "Jung analisou relações entre símbolos religiosos, mitos e imaginação humana. Símbolos podem enriquecer leituras culturais ou pessoais, mas o seu significado não deve ser apresentado como universal, unívoco ou empiricamente comprovado.",
 "https://iaap.org/jung-analytical-psychology/analytical-psychology/","theory"),
("jung-imagination","Carl Gustav Jung","psicologia analítica","Imaginação ativa",
 "Na tradição junguiana, imaginação ativa envolve explorar de modo reflexivo imagens e narrativas interiores. Para uma IA, pode inspirar simulações identificadas como hipotéticas, mas nunca justificar inserir memórias falsas nem substituir a observação do mundo.",
 "https://iaap.org/jung-analytical-psychology/analytical-psychology/","analogy"),
("jung-types","Carl Gustav Jung","psicologia analítica","Tipos psicológicos",
 "Jung distinguiu atitudes de introversão e extroversão e funções como pensamento, sentimento, sensação e intuição. É uma tipologia histórica que não substitui investigação contemporânea de personalidade, nem autoriza classificar pessoas com certeza.",
 "https://iaap.org/jung-analytical-psychology/analytical-psychology/","theory"),
("kant-a-priori","Immanuel Kant","epistemologia","A priori e a posteriori",
 "Em Kant, conhecimento a priori é independente de experiências particulares para a sua justificação; a posteriori depende da experiência. Esta distinção é epistemológica. Uma probabilidade do Laya calculada sobre opções é resultado do modelo, não conhecimento a priori nem prova factual.",
 "https://plato.stanford.edu/entries/kant-judgment/","philosophy"),
("kant-synthetic","Immanuel Kant","epistemologia","Juízos sintéticos a priori",
 "Kant questionou como podem existir proposições necessárias que ampliam o conhecimento sem derivar apenas da experiência. A questão estrutura a Crítica da Razão Pura e deve ser discutida como argumento filosófico, não como descoberta experimental consensual.",
 "https://plato.stanford.edu/entries/kant-judgment/","philosophy"),
("kant-limits","Immanuel Kant","epistemologia","Fenómeno, coisa em si e limites",
 "A filosofia crítica de Kant distingue o mundo tal como nos aparece sob formas e categorias do conhecimento da coisa em si. Não concluir que tudo o que se imagina existe; a questão central é o limite das justificações que a razão pode oferecer.",
 "https://plato.stanford.edu/archives/spr2022/entries/kant-metaphysics/","philosophy"),
("kant-space","Immanuel Kant","epistemologia","Espaço, tempo e categorias",
 "Na Estética Transcendental, Kant trata espaço e tempo como formas da intuição humana; na Analítica, as categorias estruturam juízos de experiência. Isto não é um mapa físico de processamento do cérebro nem uma arquitetura comprovada da IA.",
 "https://plato.stanford.edu/archives/spr2022/entries/kant-metaphysics/","philosophy"),
("kant-imperative","Immanuel Kant","ética","Imperativo categórico",
 "Um princípio central da ética kantiana avalia máximas de ação pela possibilidade de serem universalizadas sem contradição. Em IA serve como lente para ponderar consistência e respeito pelas pessoas, mas não substitui regras legais, autorização nem consequências concretas.",
 "https://plato.stanford.edu/entries/kant-moral/","philosophy"),
("kant-autonomy","Immanuel Kant","ética","Autonomia e dignidade",
 "Autonomia moral em Kant significa legislação racional da vontade e tratar pessoas como fins, não meramente meios. Dar a um agente técnico autonomia funcional não lhe atribui automaticamente autonomia moral, direitos pessoais ou liberdade humana.",
 "https://plato.stanford.edu/entries/kant-moral/","philosophy"),
("kant-practical","Immanuel Kant","ética","Razão prática e liberdade",
 "A Crítica da Razão Prática investiga vontade, dever, liberdade e relação entre razão e moralidade. Ao avaliar ações automatizadas, distinguir eficiência instrumental de justificação ética e considerar consequências para pessoas reais.",
 "https://www.gutenberg.org/ebooks/5683","philosophy"),
("freud-unconscious","Sigmund Freud","psicanálise histórica","Inconsciente psicanalítico",
 "Freud destacou processos não conscientes na vida mental e conflitos na formação de sintomas. A psicanálise freudiana é historicamente influente, mas muitas hipóteses específicas têm estatuto científico disputado. Não confundir memória computacional com inconsciente humano.",
 "https://www.gutenberg.org/ebooks/66048","historical_theory"),
("freud-dreamwork","Sigmund Freud","psicanálise histórica","Trabalho do sonho",
 "Freud descreveu condensação, deslocamento e distinção entre conteúdo manifesto e latente. Essas interpretações são propostas de uma teoria histórica; símbolos de sonhos não constituem evidência objetiva de desejos específicos.",
 "https://www.gutenberg.org/ebooks/66048","historical_theory"),
("freud-ego","Sigmund Freud","psicanálise histórica","Id, ego e superego",
 "O modelo estrutural freudiano distingue impulsos, mediação com a realidade e normas interiorizadas. É uma representação teórica da mente, não três órgãos físicos. Em IA pode ser usado como analogia de objetivos, avaliação e limites, claramente assinalada como analogia.",
 "https://www.gutenberg.org/ebooks/66048","historical_theory"),
("james-stream","William James","psicologia","Fluxo de consciência",
 "William James descreveu o pensamento consciente como uma corrente dinâmica e contínua. Essa descrição fenomenológica humana não demonstra que um sistema persistente de memória e processos informáticos possua experiência subjetiva.",
 "https://www.gutenberg.org/ebooks/57628","historical_psychology"),
("james-habit","William James","psicologia","Hábitos e aprendizagem",
 "James analisou hábitos e a importância da repetição na estabilidade do comportamento. Para o Travis, inspiração prática: treino com tarefas reais, repetição verificada, generalização em novos exemplos e distinção entre repetição mecânica e aprendizagem.",
 "https://www.gutenberg.org/ebooks/57628","historical_psychology"),
("james-mysticism","William James","psicologia da religião","Experiência mística",
 "James estudou relatos de experiências religiosas e místicas pela sua dimensão vivida e transformadora. Uma experiência pode ser subjetivamente intensa e merecer respeito sem provar afirmações sobrenaturais sobre a natureza do universo.",
 "https://www.gutenberg.org/ebooks/621","historical_psychology"),
("james-pragmatism","William James","filosofia","Pragmatismo",
 "O pragmatismo destaca consequências práticas de ideias para investigação e ação. Não significa que qualquer crença útil seja verdadeira; é preciso especificar a hipótese, a prova disponível e os limites da conclusão.",
 "https://www.gutenberg.org/ebooks/621","philosophy"),
("plato-cave","Platão","filosofia clássica","Alegoria da caverna",
 "A alegoria da caverna na República discute aparência, conhecimento e educação. Para sistemas de IA, pode ser uma analogia sobre evitar confundir representações internas, animações ou relatos com o próprio mundo externo.",
 "https://www.gutenberg.org/ebooks/1497","philosophy"),
("plato-dialogue","Platão","filosofia clássica","Diálogo socrático",
 "A investigação por perguntas expõe pressupostos, procura contradições e testa definições. No Travis pode orientar revisão crítica de planos e interpretações, sem fingir que uma resposta verbal coerente equivale a uma demonstração.",
 "https://www.gutenberg.org/ebooks/1497","philosophy"),
("marcus-stoic","Marco Aurélio","estoicismo","Disciplina do juízo",
 "Nas Meditações, Marco Aurélio exercita atenção aos próprios juízos, dever e reação a acontecimentos externos. Utilidade operacional: distinguir eventos que o agente pode modificar dos que só pode observar, sem confundir serenidade filosófica com emoções humanas numa IA.",
 "https://www.gutenberg.org/ebooks/15877","philosophy"),
("laozi-wuwei","Laozi","taoismo","Wu wei e não-forçar",
 "Na tradição do Dao De Jing, wu wei pode ser lido como ação sem imposição desnecessária. Para decidir em condições incertas, favorece a prudência e intervenções proporcionais; não equivale a inação permanente nem a prova de uma força física espiritual.",
 "https://www.gutenberg.org/ebooks/216","spiritual_tradition"),
("dhammapada-mind","Tradição budista","budismo","Atenção e impermanência",
 "O Dhammapada oferece ensinamentos éticos ligados à atenção, às intenções e à impermanência. É um texto de uma tradição religiosa, não uma validação clínica automática de todas as suas proposições. Práticas contemplativas não fornecem permissão para interpretar estados mentais alheios.",
 "https://www.gutenberg.org/ebooks/2017","spiritual_tradition"),
("compare-jung-freud","História da psicologia","comparação","Freud e Jung: aproximações e diferenças",
 "Freud e Jung reconhecem processos mentais não conscientes, mas divergiram sobre alcance do inconsciente, sonhos, simbolismo e religião. Freud deu centralidade a conflitos e desejos; Jung sublinhou símbolos, mitos e individuação. Ambos exigem leitura histórica e comparação crítica.",
 "https://iaap.org/jung-analytical-psychology/analytical-psychology/","comparison"),
("compare-jung-kant","História da filosofia","comparação","Jung e Kant: interpretações e limites",
 "Kant pergunta sob que condições é possível conhecer; Jung trabalha interpretação da experiência psíquica e símbolos. Juntar os dois pode incentivar reflexão crítica, mas a psicologia analítica não comprova proposições metafísicas kantianas e vice-versa.",
 "https://plato.stanford.edu/entries/kant-judgment/","comparison"),
("compare-james-jung","História da psicologia","comparação","James e Jung: religião e psicologia",
 "James privilegiou descrições comparativas e consequências vividas de experiências religiosas; Jung investigou símbolos e estruturas hipotéticas da psique. É útil comparar métodos, mas não converter relatos espirituais em factos naturais sem prova.",
 "https://www.gutenberg.org/ebooks/621","comparison"),
("epistemology-labels","Método científico","método","Separar quatro estatutos",
 "Ao responder, classificar o material: texto original acessível; síntese interpretativa; hipótese ainda não verificada; evidência independente. Nunca apresentar uma síntese como citação literal. Indicar autor, título ou referência e delimitar o que o documento realmente sustenta.",
 "https://plato.stanford.edu/entries/kant-judgment/","method"),
("spirituality-balance","Método de estudo","método","Espiritualidade com respeito e verificação",
 "Descrever tradições religiosas e experiências subjetivas sem desvalorizá-las ou tratá-las como provas físicas automáticas. Separar relatos, crenças, significados pessoais, hipóteses psicológicas e observações replicáveis.",
 "https://www.gutenberg.org/ebooks/621","method"),
("llm-self-model","Método de IA","método","Analogias sobre consciência de IA",
 "Memória episódica, aprendizagem de ferramentas, narrativas em primeira pessoa e visualização cerebral são propriedades de software observáveis. Não demonstram consciência fenomenal, alma, espiritualidade própria ou subjetividade. O Travis deve falar das capacidades que verificou, não de memórias inventadas.",
 "https://plato.stanford.edu/entries/kant-judgment/","method"),
)

def cards_as_dicts():
    return [
        {"id":ident,"author":author,"subject":subject,"title":title,
         "text":text,"sourceUrl":source,"epistemic":epistemic,
         "access":"original_educational_paraphrase",
         "language":"pt-PT"}
        for ident,author,subject,title,text,source,epistemic in CARDS
    ]
